/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from '@tanstack/react-start/server'

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { ServerRoute as ApiWordResponseServerRouteImport } from './routes/api/word-response'
import { ServerRoute as ApiWordOfTheDayServerRouteImport } from './routes/api/word-of-the-day'
import { ServerRoute as ApiWebhookServerRouteImport } from './routes/api/webhook'
import { ServerRoute as ApiUsersServerRouteImport } from './routes/api/users'
import { ServerRoute as ApiUserGuildsServerRouteImport } from './routes/api/user-guilds'
import { ServerRoute as ApiSystemPromptServerRouteImport } from './routes/api/system-prompt'
import { ServerRoute as ApiRecordUserMessageServerRouteImport } from './routes/api/record-user-message'
import { ServerRoute as ApiLyricsServerRouteImport } from './routes/api/lyrics'
import { ServerRoute as ApiLeaderboardServerRouteImport } from './routes/api/leaderboard'
import { ServerRoute as ApiGuildsServerRouteImport } from './routes/api/guilds'
import { ServerRoute as ApiEnsureUserGuildExistsServerRouteImport } from './routes/api/ensure-user-guild-exists'
import { ServerRoute as ApiChannelsServerRouteImport } from './routes/api/channels'
import { ServerRoute as ApiUsersUserIdServerRouteImport } from './routes/api/users/$userId'
import { ServerRoute as ApiLyricsTitleServerRouteImport } from './routes/api/lyrics/$title'
import { ServerRoute as ApiGuildsGuildIdServerRouteImport } from './routes/api/guilds/$guildId'
import { ServerRoute as ApiChannelsChannelIdServerRouteImport } from './routes/api/channels/$channelId'
import { ServerRoute as ApiLyricsArtistTitleServerRouteImport } from './routes/api/lyrics/$artist/$title'

const rootServerRouteImport = createServerRootRoute()

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWordResponseServerRoute = ApiWordResponseServerRouteImport.update({
  id: '/api/word-response',
  path: '/api/word-response',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiWordOfTheDayServerRoute = ApiWordOfTheDayServerRouteImport.update({
  id: '/api/word-of-the-day',
  path: '/api/word-of-the-day',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiWebhookServerRoute = ApiWebhookServerRouteImport.update({
  id: '/api/webhook',
  path: '/api/webhook',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersServerRoute = ApiUsersServerRouteImport.update({
  id: '/api/users',
  path: '/api/users',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUserGuildsServerRoute = ApiUserGuildsServerRouteImport.update({
  id: '/api/user-guilds',
  path: '/api/user-guilds',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiSystemPromptServerRoute = ApiSystemPromptServerRouteImport.update({
  id: '/api/system-prompt',
  path: '/api/system-prompt',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiRecordUserMessageServerRoute =
  ApiRecordUserMessageServerRouteImport.update({
    id: '/api/record-user-message',
    path: '/api/record-user-message',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiLyricsServerRoute = ApiLyricsServerRouteImport.update({
  id: '/api/lyrics',
  path: '/api/lyrics',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiLeaderboardServerRoute = ApiLeaderboardServerRouteImport.update({
  id: '/api/leaderboard',
  path: '/api/leaderboard',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiGuildsServerRoute = ApiGuildsServerRouteImport.update({
  id: '/api/guilds',
  path: '/api/guilds',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiEnsureUserGuildExistsServerRoute =
  ApiEnsureUserGuildExistsServerRouteImport.update({
    id: '/api/ensure-user-guild-exists',
    path: '/api/ensure-user-guild-exists',
    getParentRoute: () => rootServerRouteImport,
  } as any)
const ApiChannelsServerRoute = ApiChannelsServerRouteImport.update({
  id: '/api/channels',
  path: '/api/channels',
  getParentRoute: () => rootServerRouteImport,
} as any)
const ApiUsersUserIdServerRoute = ApiUsersUserIdServerRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => ApiUsersServerRoute,
} as any)
const ApiLyricsTitleServerRoute = ApiLyricsTitleServerRouteImport.update({
  id: '/$title',
  path: '/$title',
  getParentRoute: () => ApiLyricsServerRoute,
} as any)
const ApiGuildsGuildIdServerRoute = ApiGuildsGuildIdServerRouteImport.update({
  id: '/$guildId',
  path: '/$guildId',
  getParentRoute: () => ApiGuildsServerRoute,
} as any)
const ApiChannelsChannelIdServerRoute =
  ApiChannelsChannelIdServerRouteImport.update({
    id: '/$channelId',
    path: '/$channelId',
    getParentRoute: () => ApiChannelsServerRoute,
  } as any)
const ApiLyricsArtistTitleServerRoute =
  ApiLyricsArtistTitleServerRouteImport.update({
    id: '/$artist/$title',
    path: '/$artist/$title',
    getParentRoute: () => ApiLyricsServerRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/dashboard'
  id: '__root__' | '/' | '/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
}
export interface FileServerRoutesByFullPath {
  '/api/channels': typeof ApiChannelsServerRouteWithChildren
  '/api/ensure-user-guild-exists': typeof ApiEnsureUserGuildExistsServerRoute
  '/api/guilds': typeof ApiGuildsServerRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardServerRoute
  '/api/lyrics': typeof ApiLyricsServerRouteWithChildren
  '/api/record-user-message': typeof ApiRecordUserMessageServerRoute
  '/api/system-prompt': typeof ApiSystemPromptServerRoute
  '/api/user-guilds': typeof ApiUserGuildsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/webhook': typeof ApiWebhookServerRoute
  '/api/word-of-the-day': typeof ApiWordOfTheDayServerRoute
  '/api/word-response': typeof ApiWordResponseServerRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdServerRoute
  '/api/guilds/$guildId': typeof ApiGuildsGuildIdServerRoute
  '/api/lyrics/$title': typeof ApiLyricsTitleServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/lyrics/$artist/$title': typeof ApiLyricsArtistTitleServerRoute
}
export interface FileServerRoutesByTo {
  '/api/channels': typeof ApiChannelsServerRouteWithChildren
  '/api/ensure-user-guild-exists': typeof ApiEnsureUserGuildExistsServerRoute
  '/api/guilds': typeof ApiGuildsServerRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardServerRoute
  '/api/lyrics': typeof ApiLyricsServerRouteWithChildren
  '/api/record-user-message': typeof ApiRecordUserMessageServerRoute
  '/api/system-prompt': typeof ApiSystemPromptServerRoute
  '/api/user-guilds': typeof ApiUserGuildsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/webhook': typeof ApiWebhookServerRoute
  '/api/word-of-the-day': typeof ApiWordOfTheDayServerRoute
  '/api/word-response': typeof ApiWordResponseServerRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdServerRoute
  '/api/guilds/$guildId': typeof ApiGuildsGuildIdServerRoute
  '/api/lyrics/$title': typeof ApiLyricsTitleServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/lyrics/$artist/$title': typeof ApiLyricsArtistTitleServerRoute
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport
  '/api/channels': typeof ApiChannelsServerRouteWithChildren
  '/api/ensure-user-guild-exists': typeof ApiEnsureUserGuildExistsServerRoute
  '/api/guilds': typeof ApiGuildsServerRouteWithChildren
  '/api/leaderboard': typeof ApiLeaderboardServerRoute
  '/api/lyrics': typeof ApiLyricsServerRouteWithChildren
  '/api/record-user-message': typeof ApiRecordUserMessageServerRoute
  '/api/system-prompt': typeof ApiSystemPromptServerRoute
  '/api/user-guilds': typeof ApiUserGuildsServerRoute
  '/api/users': typeof ApiUsersServerRouteWithChildren
  '/api/webhook': typeof ApiWebhookServerRoute
  '/api/word-of-the-day': typeof ApiWordOfTheDayServerRoute
  '/api/word-response': typeof ApiWordResponseServerRoute
  '/api/channels/$channelId': typeof ApiChannelsChannelIdServerRoute
  '/api/guilds/$guildId': typeof ApiGuildsGuildIdServerRoute
  '/api/lyrics/$title': typeof ApiLyricsTitleServerRoute
  '/api/users/$userId': typeof ApiUsersUserIdServerRoute
  '/api/lyrics/$artist/$title': typeof ApiLyricsArtistTitleServerRoute
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath
  fullPaths:
    | '/api/channels'
    | '/api/ensure-user-guild-exists'
    | '/api/guilds'
    | '/api/leaderboard'
    | '/api/lyrics'
    | '/api/record-user-message'
    | '/api/system-prompt'
    | '/api/user-guilds'
    | '/api/users'
    | '/api/webhook'
    | '/api/word-of-the-day'
    | '/api/word-response'
    | '/api/channels/$channelId'
    | '/api/guilds/$guildId'
    | '/api/lyrics/$title'
    | '/api/users/$userId'
    | '/api/lyrics/$artist/$title'
  fileServerRoutesByTo: FileServerRoutesByTo
  to:
    | '/api/channels'
    | '/api/ensure-user-guild-exists'
    | '/api/guilds'
    | '/api/leaderboard'
    | '/api/lyrics'
    | '/api/record-user-message'
    | '/api/system-prompt'
    | '/api/user-guilds'
    | '/api/users'
    | '/api/webhook'
    | '/api/word-of-the-day'
    | '/api/word-response'
    | '/api/channels/$channelId'
    | '/api/guilds/$guildId'
    | '/api/lyrics/$title'
    | '/api/users/$userId'
    | '/api/lyrics/$artist/$title'
  id:
    | '__root__'
    | '/api/channels'
    | '/api/ensure-user-guild-exists'
    | '/api/guilds'
    | '/api/leaderboard'
    | '/api/lyrics'
    | '/api/record-user-message'
    | '/api/system-prompt'
    | '/api/user-guilds'
    | '/api/users'
    | '/api/webhook'
    | '/api/word-of-the-day'
    | '/api/word-response'
    | '/api/channels/$channelId'
    | '/api/guilds/$guildId'
    | '/api/lyrics/$title'
    | '/api/users/$userId'
    | '/api/lyrics/$artist/$title'
  fileServerRoutesById: FileServerRoutesById
}
export interface RootServerRouteChildren {
  ApiChannelsServerRoute: typeof ApiChannelsServerRouteWithChildren
  ApiEnsureUserGuildExistsServerRoute: typeof ApiEnsureUserGuildExistsServerRoute
  ApiGuildsServerRoute: typeof ApiGuildsServerRouteWithChildren
  ApiLeaderboardServerRoute: typeof ApiLeaderboardServerRoute
  ApiLyricsServerRoute: typeof ApiLyricsServerRouteWithChildren
  ApiRecordUserMessageServerRoute: typeof ApiRecordUserMessageServerRoute
  ApiSystemPromptServerRoute: typeof ApiSystemPromptServerRoute
  ApiUserGuildsServerRoute: typeof ApiUserGuildsServerRoute
  ApiUsersServerRoute: typeof ApiUsersServerRouteWithChildren
  ApiWebhookServerRoute: typeof ApiWebhookServerRoute
  ApiWordOfTheDayServerRoute: typeof ApiWordOfTheDayServerRoute
  ApiWordResponseServerRoute: typeof ApiWordResponseServerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}
declare module '@tanstack/react-start/server' {
  interface ServerFileRoutesByPath {
    '/api/word-response': {
      id: '/api/word-response'
      path: '/api/word-response'
      fullPath: '/api/word-response'
      preLoaderRoute: typeof ApiWordResponseServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/word-of-the-day': {
      id: '/api/word-of-the-day'
      path: '/api/word-of-the-day'
      fullPath: '/api/word-of-the-day'
      preLoaderRoute: typeof ApiWordOfTheDayServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/webhook': {
      id: '/api/webhook'
      path: '/api/webhook'
      fullPath: '/api/webhook'
      preLoaderRoute: typeof ApiWebhookServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users': {
      id: '/api/users'
      path: '/api/users'
      fullPath: '/api/users'
      preLoaderRoute: typeof ApiUsersServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/user-guilds': {
      id: '/api/user-guilds'
      path: '/api/user-guilds'
      fullPath: '/api/user-guilds'
      preLoaderRoute: typeof ApiUserGuildsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/system-prompt': {
      id: '/api/system-prompt'
      path: '/api/system-prompt'
      fullPath: '/api/system-prompt'
      preLoaderRoute: typeof ApiSystemPromptServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/record-user-message': {
      id: '/api/record-user-message'
      path: '/api/record-user-message'
      fullPath: '/api/record-user-message'
      preLoaderRoute: typeof ApiRecordUserMessageServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/lyrics': {
      id: '/api/lyrics'
      path: '/api/lyrics'
      fullPath: '/api/lyrics'
      preLoaderRoute: typeof ApiLyricsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/leaderboard': {
      id: '/api/leaderboard'
      path: '/api/leaderboard'
      fullPath: '/api/leaderboard'
      preLoaderRoute: typeof ApiLeaderboardServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/guilds': {
      id: '/api/guilds'
      path: '/api/guilds'
      fullPath: '/api/guilds'
      preLoaderRoute: typeof ApiGuildsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/ensure-user-guild-exists': {
      id: '/api/ensure-user-guild-exists'
      path: '/api/ensure-user-guild-exists'
      fullPath: '/api/ensure-user-guild-exists'
      preLoaderRoute: typeof ApiEnsureUserGuildExistsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/channels': {
      id: '/api/channels'
      path: '/api/channels'
      fullPath: '/api/channels'
      preLoaderRoute: typeof ApiChannelsServerRouteImport
      parentRoute: typeof rootServerRouteImport
    }
    '/api/users/$userId': {
      id: '/api/users/$userId'
      path: '/$userId'
      fullPath: '/api/users/$userId'
      preLoaderRoute: typeof ApiUsersUserIdServerRouteImport
      parentRoute: typeof ApiUsersServerRoute
    }
    '/api/lyrics/$title': {
      id: '/api/lyrics/$title'
      path: '/$title'
      fullPath: '/api/lyrics/$title'
      preLoaderRoute: typeof ApiLyricsTitleServerRouteImport
      parentRoute: typeof ApiLyricsServerRoute
    }
    '/api/guilds/$guildId': {
      id: '/api/guilds/$guildId'
      path: '/$guildId'
      fullPath: '/api/guilds/$guildId'
      preLoaderRoute: typeof ApiGuildsGuildIdServerRouteImport
      parentRoute: typeof ApiGuildsServerRoute
    }
    '/api/channels/$channelId': {
      id: '/api/channels/$channelId'
      path: '/$channelId'
      fullPath: '/api/channels/$channelId'
      preLoaderRoute: typeof ApiChannelsChannelIdServerRouteImport
      parentRoute: typeof ApiChannelsServerRoute
    }
    '/api/lyrics/$artist/$title': {
      id: '/api/lyrics/$artist/$title'
      path: '/$artist/$title'
      fullPath: '/api/lyrics/$artist/$title'
      preLoaderRoute: typeof ApiLyricsArtistTitleServerRouteImport
      parentRoute: typeof ApiLyricsServerRoute
    }
  }
}

interface ApiChannelsServerRouteChildren {
  ApiChannelsChannelIdServerRoute: typeof ApiChannelsChannelIdServerRoute
}

const ApiChannelsServerRouteChildren: ApiChannelsServerRouteChildren = {
  ApiChannelsChannelIdServerRoute: ApiChannelsChannelIdServerRoute,
}

const ApiChannelsServerRouteWithChildren =
  ApiChannelsServerRoute._addFileChildren(ApiChannelsServerRouteChildren)

interface ApiGuildsServerRouteChildren {
  ApiGuildsGuildIdServerRoute: typeof ApiGuildsGuildIdServerRoute
}

const ApiGuildsServerRouteChildren: ApiGuildsServerRouteChildren = {
  ApiGuildsGuildIdServerRoute: ApiGuildsGuildIdServerRoute,
}

const ApiGuildsServerRouteWithChildren = ApiGuildsServerRoute._addFileChildren(
  ApiGuildsServerRouteChildren,
)

interface ApiLyricsServerRouteChildren {
  ApiLyricsTitleServerRoute: typeof ApiLyricsTitleServerRoute
  ApiLyricsArtistTitleServerRoute: typeof ApiLyricsArtistTitleServerRoute
}

const ApiLyricsServerRouteChildren: ApiLyricsServerRouteChildren = {
  ApiLyricsTitleServerRoute: ApiLyricsTitleServerRoute,
  ApiLyricsArtistTitleServerRoute: ApiLyricsArtistTitleServerRoute,
}

const ApiLyricsServerRouteWithChildren = ApiLyricsServerRoute._addFileChildren(
  ApiLyricsServerRouteChildren,
)

interface ApiUsersServerRouteChildren {
  ApiUsersUserIdServerRoute: typeof ApiUsersUserIdServerRoute
}

const ApiUsersServerRouteChildren: ApiUsersServerRouteChildren = {
  ApiUsersUserIdServerRoute: ApiUsersUserIdServerRoute,
}

const ApiUsersServerRouteWithChildren = ApiUsersServerRoute._addFileChildren(
  ApiUsersServerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiChannelsServerRoute: ApiChannelsServerRouteWithChildren,
  ApiEnsureUserGuildExistsServerRoute: ApiEnsureUserGuildExistsServerRoute,
  ApiGuildsServerRoute: ApiGuildsServerRouteWithChildren,
  ApiLeaderboardServerRoute: ApiLeaderboardServerRoute,
  ApiLyricsServerRoute: ApiLyricsServerRouteWithChildren,
  ApiRecordUserMessageServerRoute: ApiRecordUserMessageServerRoute,
  ApiSystemPromptServerRoute: ApiSystemPromptServerRoute,
  ApiUserGuildsServerRoute: ApiUserGuildsServerRoute,
  ApiUsersServerRoute: ApiUsersServerRouteWithChildren,
  ApiWebhookServerRoute: ApiWebhookServerRoute,
  ApiWordOfTheDayServerRoute: ApiWordOfTheDayServerRoute,
  ApiWordResponseServerRoute: ApiWordResponseServerRoute,
}
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>()
